name: dirsize
version: '2.2.18'
summary: The Command line Directory Reporting Tool
description: |
   DirSize is a directory reporting tool. It recursively scans
   the provided (or current) directory, and reports the
   number of files and director sizes of each subdirectory present.

grade: stable
confinement: strict
base: core18

title: DirSize
website: https://github.com/frossm/dirsize
issues: https://github.com/frossm/dirsize/issues
license: MIT

# Enable faszter LZO compression
compression: lzo

apps:
  dirsize:
    command: dirsize-wrapper
    plugs:
      - system-backup
      - home
      - network

parts:
  wrapper:
    plugin: dump
    source: snap/local
    source-type: local
    
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2022.11.21'
    maven-options: [install]

  dirsize:
    plugin: maven
    source: https://github.com/frossm/dirsize.git
    source-branch: master
    source-type: git
    after: [library]
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
