name: dirsize
version: '2.2.7'
summary: The Command line Directory Reporting Tool
description: |
   DirSize is a directory reporting tool. It recursively scans
   the provided (or current) directory, and reports the 
   number of files and director sizes of each subdirectory present.

grade: stable 
confinement: strict
base: core18

# Enable faszter LZO compression
compression: lzo

apps:
  dirsize:
    command: bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/dirsize.jar

    plugs:
    - network
    - system-backup
    
parts:
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2021.05.16'
    maven-options: [install]

  dirsize:
    plugin: maven
    source: https://github.com/frossm/dirsize.git
    source-branch: master
    source-type: git
    after: [library]
