name: dirsize
version: '2.2.23'
summary: The Command line Directory Reporting Tool
description: |
   DirSize is a directory reporting tool. It recursively scans
   the provided (or current) directory, and reports the
   number of files and director sizes of each subdirectory present.

grade: stable
confinement: strict
base: core22

title: DirSize
website: https://github.com/frossm/dirsize
issues: https://github.com/frossm/dirsize/issues
license: MIT

# Enable faszter LZO compression
compression: lzo

# Ignore useless library warnings
lint:
  ignore:
    - library

apps:
  dirsize:
    command: dirsize-wrapper
    plugs:
      - system-backup
      - home
      - network

parts:
  wrapper:
    plugin: dump
    source: snap/local
    source-type: local
    
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2023.07.14'
    maven-parameters:
      - install
    
    build-packages:
      - maven
      - openjdk-11-jdk-headless

  dirsize:
    plugin: maven
    source: https://github.com/frossm/dirsize.git
    source-branch: master
    source-type: git
    after: 
      - library
    
    build-packages:
      - maven
      - openjdk-11-jdk-headless

    stage-packages:
      - openjdk-11-jre-headless
    
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
